### PR TITLE
Fix the excluding example

### LINKED ISSUE #30: External bundles
As explain here: https://github.com/substack/browserify-handbook#external-bundles
I do the following:

```
npm install jquery
browserify -r jquery --standalone jquery > jquery-bundle.js
browserify main.js --exclude jquery > bundle.js
```

index.html:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>My Site</title>
  <script src="jquery-bundle.js"></script>
  <script src="bundle.js"></script>
</head>
<body>
    <h1>My Site</h1>
</body>
</html>
```

main.js:

```
var $ = require('jquery');
$(window).click(function () { document.body.bgColor = 'red' });
```

And when I open my page I get Uncaught Error: Cannot find module 'jquery'

Is it a code bug, a doc bug or am I just missing something ?

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #30

### CODE REVIEW

**Comment by inuscript** [comment]
+1

**Comment by tschaub** [comment]
I'm not sure which is more or less mysterious, but an alternative is to correct this example to suggest:
```
$ browserify -r jquery --standalone jQuery > jquery-bundle.js
```

(instead of `--standalone jquery`)

**Comment by tschaub** [comment]
As mentioned in #62, I think your fix here is better - as people will get into trouble trying to use `--standalone` for more non-jquery cases.

**Comment by goto-bus-stop** [comment]
Thanks!

**Pull request merged**
